# Constants for analysis exclusions and keyword lists

# Common language connectors in Portuguese to be excluded from analysis
LANGUAGE_CONNECTORS = {
    "msm", "eu", "mas", "vai", "nn", "ta","tem", "vou", "só", "e", "é", "eh", "que", "q", "de", "da", "do", "das", "dos", "a", "á", "à", "ah", "o", "os", "em", "no", "na", "nos", 
    "nas", "por", "pra", "pro", "para", "p", "com", "c", "um", "uma", "umas", "uns", "ao", "aos", "ele", "ela", "eles", 
    "elas", "seu", "sua", "seus", "suas", "um", "uma", "uns", "umas", "meu", "minha", "meus", "minhas", "nosso", "nossa", 
    "nossos", "nossas", "este", "esta", "estes", "estas", "esse", "essa", "esses", "essas", "aquele", "aquela", "aqueles", 
    "aquelas", "isto", "isso", "aquilo", "mais", "mais", "mto", "mt", "muito", "mta", "muita", "muitos", "muitas", "menos", 
    "pouco", "pouca", "poucos", "poucas", "muitíssimo", "muitíssima", "muitíssimos", "muitíssimas", "demais", "d+", "tb", 
    "tbm", "também", "tmb", "não", "nao", "n", "ñ", "sim", "s", "talvez", "vez", "vezes", "sobre", "sob", "sem", "s", 
    "dentro", "fora", "antes", "depois", "agora", "já", "ja", "logo", "ainda", "já", "ja", "logo", "ainda", "até", "ate", 
    "depois", "durante", "enquanto", "vc", "você", "voce", "vcs", "vocês", "voces", "tu", "te", "ti", "teu", "tua", "teus", 
    "tuas", "ele", "ela", "eles", "elas", "me", "mim", "comigo", "nos", "conosco", "vos", "convosco", "lhe", "lhes", 
    "si", "consigo", "o", "a", "os", "as", "lo", "la", "los", "las", "me", "te", "se", "nos", "vos", "o", "a", "os", "as", 
    "lo", "la", "los", "las", "me", "te", "se", "nos", "vos", "este", "esta", "estes", "estas", "esse", "essa", "esses", 
    "essas", "aquele", "aquela", "aqueles", "aquelas", "isto", "isso", "aquilo", "algum", "alguma", "alguns", "algumas", 
    "nenhum", "nenhuma", "nenhuns", "nenhumas", "todo", "toda", "todos", "todas", "outro", "outra", "outros", "outras", 
    "muito", "muita", "muitos", "muitas", "pouco", "pouca", "poucos", "poucas", "bastante", "bastantes", "cada", "varios", 
    "varias", "qualquer", "quaisquer", "tal", "tais", "tanto", "tanta", "tantos", "tantas", "quanto", "quanta", "quantos", 
    "quantas", "um", "uma", "uns", "umas", "certo", "certa", "certos", "certas", "vário", "vária", "vários", "várias", 
    "mesmo", "mesma", "mesmos", "mesmas", "tão", "tamanho", "quanto", "quanta", "quantos", "quantas", "quanto", "quanta", 
    "quantos", "quantas", "qual", "quais", "cujo", "cuja", "cujos", "cujas", "quem", "onde", "como", "quando", "porque", 
    "pq", "q", "pois", "por", "para", "per", "pera", "dum", "duma", "duns", "dumas", "num", "numa", "nuns", "numas", 
    "pelo", "pela", "pelos", "pelas", "de", "do", "da", "dos", "das", "d", "deste", "desta", "destes", "destas", "desse", 
    "dessa", "desses", "dessas", "daquele", "daquela", "daqueles", "daquelas", "deste", "desta", "destes", "destas", 
    "desse", "dessa", "desses", "dessas", "daquele", "daquela", "daqueles", "daquelas", "a", "ao", "aos", "à", "às", 
    "dum", "duma", "duns", "dumas", "num", "numa", "nuns", "numas", "com", "co", "sen", "seno", "pra", "pro", "pras", 
    "pros", "p", "pa", "em", "no", "na", "nos", "nas", "n", "num", "numa", "nuns", "numas", "por", "pelo", "pela", "pelos", 
    "pelas", "p", "po", "dentre", "entre", "ate", "até", "a", "para", "perante", "sob", "sobre", "tras", "trás", "após", 
    "depois", "desde", "durante", "excepto", "exceto", "fora", "mediante", "salvo", "segundo", "sem", "tirante", "c", "com", 
    "conforme", "consoante", "conforme", "consoante", "conforme", "consoante", "segundo", "segundo", "segundo", "como", 
    "como", "como", "conforme", "consoante", "conforme", "consoante", "conforme", "consoante", "segundo", "segundo", 
    "segundo", "como", "como", "como", "segundo", "segundo", "segundo", "como", "como", "como", "blz", "flw", "vlw", "abs", "bjs", "bj", "tchau", "né", "néh", "sqn", "slc", "tipo", "tipow", "mano", 
    "man", "mana", "manos", "manas", "cara", "fdp", "aff", "afff", "rs", "haha", "kkk", "kkkk", "kkkkk", 
    "hahaha", "hehe", "hehehe", "hm", "hmm", "hmmm", "aham", "aha", "uhu", "ops", "epa", "olha", "veja", 
    "tipo assim", "sei lá", "seilá", "sei la", "seila", "enfim", "então", "dai", "daí", "entendeu", "entende", 
    "sacou", "saca", "certo", "beleza", "tranquilo", "tranquila", "suave", "na boa", "de boa", "demorou", 
    "bora", "vamo", "vamos", "partiu", "bora lá", "falou", "fui", "falo", "fala", "falando", "dizendo", 
    "digo", "diz", "dizer", "falava", "falou", "disse", "falasse", "falaria", "diria", "pois é", "poisé", 
    "pois é", "tá ligado", "tá ligada", "manja", "manjo", "sabe", "sabendo", "sacando", "captando", "percebe", 
    "percebendo", "entendendo", "captou", "captou?", "sacou?", "sacou", "entendeu?", "entendeu", "percebeu?", 
    "percebeu", "viu", "vendo", "ver", "olhando", "escuta", "escutando", "ouça", "ouvindo", "ouvindo", "ouvi", 
    "ouviu", "ouvir", "ouvia", "ouvirei", "ouviria", "ouvisse", "sentindo", "sente", "senti", "sente", "sentir", 
    "sentia", "sentirá", "sentiria", "sentisse", "pensando", "pensa", "penso", "pensou", "pensar", "pensava", 
    "pensaria", "pensasse",
}

# Lists of words associated with specific sentiments
HAPPY_WORDS = {
    "feliz", "alegre", "contente", "sorridente", "sorriso", "amor", "entusiasmado", "entusiasmada", "animado", "animada",
    "vibrante", "radiante", "eufórico", "eufórica", "maravilhoso", "maravilhosa", "fantástico", "fantástica", "incrível",
    "espetacular", "excelente", "ótimo", "ótima", "formidável", "positivo", "positiva", "energético", "energética",
    "apaixonado", "apaixonada", "empolgado", "empolgada", "festejar", "celebrar", "vitorioso", "vitoriosa", "triunfante",
    "divertido", "divertida", "brilhante", "luminoso", "luminosa", "deslumbrante", "deslumbrado", "deslumbrada",
    "entusiasmo", "animação", "felicidade", "alegria", "júbilo", "jovial", "jovialidade", "vivaz", "viva", "vigoroso",
    "vigorosa", "dinâmico", "dinâmica", "vibrar", "exultar", "comemorar", "festa", "celebração", "gargalhada", "risada",
    "risonho", "risonha", "riso", "gargalhar", "rir", "risadas", "hilário", "hilária", "humor", "piada", "brincadeira",
    "diversão", "prazer", "gosto", "gostar", "adorar", "paixão", "encantado", "encantada", "encanto", "magia", "mágico",
    "mágica", "sonho", "sonhar", "esperança", "esperançoso", "esperançosa", "otimismo", "otimista", "sucesso", "bem-sucedido",
    "bem-sucedida", "realização", "realizado", "realizada", "conquista", "conquistar", "vitória", "ganhar", "ganho",
    "lucro", "benefício", "vantagem", "progresso", "avanço", "melhoria", "fascinado", "fascinada", "fascinação",
    "gratidão", "grato", "grata", "agradecido", "agradecida", "agradecer", "bondade", "gentileza", "carinho", "afeto",
    "afetividade", "amigável", "amizade", "companheirismo", "companheiro", "companheira", "parceiro", "parceira",
    "união", "unido", "unida", "junto", "junta", "juntos", "juntas", "coletivo", "coletiva", "grupo", "equipe",
    "colaboração", "colaborar", "ajuda", "ajudar", "apoio", "apoiar", "suporte", "entendimento", "compreensão",
    "aceitação", "aceitar", "respeito", "respeitar", "admiração", "admirar", "inspiração", "inspirar", "motivação",
    "motivar", "estímulo", "estimular", "crescimento", "crescer", "desenvolvimento", "desenvolver", "aprendizado",
    "aprender", "conhecimento", "conhecer", "sabedoria", "sábio", "sábia", "inteligência", "inteligente", "capacidade",
    "habilidade", "talento", "dotado", "dotada", "dotar", "criatividade", "criativo", "criativa", "inovar", "inovação",
    "inovador", "inovadora", "original", "originalidade", "único", "única", "singular", "especial", "extraordinário",
    "extraordinária", "excepcional", "notável", "destacado", "destacada", "líder", "liderança", "liderar", "comando",
    "comandar", "direção", "dirigir", "orientação", "orientar", "guiar", "guia", "caminho", "caminhar", "percurso",
    "trajetória", "viagem", "viajar", "aventura", "aventurar", "explorar", "exploração", "descoberta", "descobrir",
    "inovação", "inovar", "novidade", "novo", "nova", "renovar", "renovação", "mudança", "mudar", "transformação",
    "transformar", "transição", "transitar", "evolução", "evoluir", "progresso", "progredir", "avanço", "avançar",
    "melhoria", "melhorar", "benefício", "beneficiar", "vantagem", "vantajoso", "vantajosa", "ganho", "ganhar",
    "lucro", "lucrar", "sucesso", "bem-sucedido", "bem-sucedida", "realização", "realizar", "conquista", "conquistar",
    "vitória", "vencer", "triunfo", "triunfar", "superação", "superar", "desafio", "desafiar", "obstáculo", "superar",
    "barreira", "transpor", "solução", "resolver", "resolução", "resultado", "atingir", "alcance", "alcançar",
    "objetivo", "meta", "propósito", "intenção", "intencionar", "foco", "focar", "direção", "direcionar", "rumo",
    "seguir", "continuar", "persistência", "persistir", "esforço", "esforçar", "trabalho", "trabalhar", "dedicação",
    "dedicar", "empenho", "empenhar", "compromisso", "comprometer", "responsabilidade", "responsabilizar", "encargo",
    "encarregar", "tarefa", "realizar", "execução", "executar", "ação", "agir", "atividade", "ativar", "operação",
    "operar", "funcionamento", "funcionar", "desempenho", "desempenhar", "capacidade", "capacitar", "habilidade",
    "habilitar", "competência", "competente", "aptidão", "apto", "apta", "qualificação", "qualificar", "preparação",
    "preparar", "formação", "formar", "educação", "educar", "ensino", "ensinar", "aprendizagem", "aprender",
    "conhecimento", "conhecer", "entendimento", "entender", "compreensão", "compreender", "percepção", "perceber",
    "visão", "vislumbrar", "perspectiva", "perspectivar", "análise", "analisar", "avaliação", "avaliar", "julgamento",
    "julgar", "opinião", "opinar", "pensamento", "pensar", "ideia", "idealizar", "criatividade", "criativo", "criativa",
    "inovação", "inovar", "inventividade", "inventivo", "inventiva", "originalidade", "original", "original",
    "autenticidade", "autêntico", "autêntica", "singularidade", "singular", "singular", "exclusividade", "exclusivo",
    "exclusiva", "unicidade", "único", "única", "diferença", "diferenciar", "distinção", "distinguir", "especialidade",
    "especial", "especial",
}

SAD_WORDS = {
    "triste", "infeliz", "deprimido", "chorando", "lágrimas", "sofrimento", "dor", "sofrer", "angústia", "desespero", 
    "solidão", "saudade", "melancolia", "desânimo", "desilusão", "desolado", "desconsolado", "magoado", "amargurado", 
    "pessimismo", "nostalgia", "aflição", "insegurança", "medo", "ansiedade", "preocupação", "desgosto", "pena", 
    "remorso", "arrependimento", "culpa", "fracasso", "derrota", "perda", "sombrio", "abandonado", "desamparo", 
    "desesperança", "agonia", "pesar", "vazio", "apático", "cansado", "exausto", "oprimido", "sufocado", "claustrofobia", 
    "obsessão", "paranoia", "pavor", "terror", "horror", "desconfiança", "ciúme", "inveja", "rancor", "ódio", "aversão", 
    "repulsa", "desprezo", "desinteresse", "indiferença", "frio", "distante", "isolado", "isolamento", "alienação", 
    "negligência", "abuso", "trauma", "traumático", "ferida", "ferido", "machucado", "dano", "danificado", "quebrado", 
    "destruído", "ruína", "desastre", "catástrofe", "crise", "turbulência", "conflito", "batalha", "guerra", 
    "desacordo", "discordância", "contenda", "disputa", "rivalidade", "inimizade", "hostilidade", "agressão", 
    "violência", "briga", "confronto", "enfrentamento", "desafio", "obstáculo", "barreira", "impedimento", 
    "limitação", "restrição", "proibição", "negativo", "negatividade", "pessimista", "fatalista", "derrotista", 
    "cético", "ceticismo", "dúvida", "incerteza", "indecisão", "hesitação", "ambiguidade", "confusão", "desorientação", 
    "perplexidade", "complexo", "complicado", "difícil", "duro", "árduo", "penoso", "trabalhoso", "exigente", 
    "esforço", "luta", "batalhar", "esforçar", "tentar", "tentativa", "falha", "falta", "deficiência", "carência", 
    "necessidade", "precisão", "urgência", "emergência", "crítico", "grave", "sério", "profundo", "intenso", 
    "extremo", "excessivo", "demasiado", "sobrecarga", "sobrecarregado", "pressão", "estresse", "estressado", 
    "tenso", "tensão", "nervoso", "nervosismo", "irritado", "irritação", "frustrado", "frustração", "descontentamento", 
    "insatisfação", "desapontamento", "decepção", "desencanto", "desiludido", "cético", "descrente", "incrédulo", 
    "duvidoso", "questionável", "problemático", "problema", "questão", "dilema", "impasse", "estagnação", "paralisia", 
    "imobilidade", "inércia", "letargia", "sonolência", "cansaço", "fadiga", "exaustão", "debilitado", "enfraquecido", 
    "fragilizado", "vulnerável", "exposto", "desprotegido", "indefeso", "impotente", "desamparado", "desassistido", 
    "desvalido", "abandonado", "desprezado", "rejeitado", "descartado", "ignorado", "esquecido", "omitido", 
    "negligenciado", "despreocupado", "desatento", "descuidado", "relapso", "indolente", "preguiçoso", "ocioso", 
    "inativo", "inoperante", "inútil", "improdutivo", "esteril", "infértil", "vão", "fútil", "supérfluo", 
    "dispensável", "desnecessário", "inadequado", "inapropriado", "impróprio", "incorreto", "errado", "equivocado", 
    "enganado", "iludido", "fantasiado", "fictício", "irreal", "utópico", "impossível", "impraticável"
}

LOVE_WORDS = {
    "amor", "querido", "querida", "apaixonado", "apaixonada", "saudade", "coelhinha", "princesa", "gato", "gata", 
    "gostoso", "gostosa", "lindo", "linda", "carinho", "afeto", "paixão", "adoro", "adorar", "beijo", "beijos", 
    "abraço", "abraços", "meu bem", "minha vida", "coração", "docinho", "amorzinho", "querida", "querido", "fofo", 
    "fofa", "tesouro", "vida", "alma gêmea", "cumplicidade", "companheirismo", "amizade", "afeto", "afetuoso", 
    "afetuosa", "carinhoso", "carinhosa", "ternura", "meiga", "meigo", "encanto", "encantador", "encantadora", 
    "gracinha", "preciosa", "precioso", "joia", "raridade", "única", "único", "especial", "amada", "amado", 
    "idolatrada", "idolatrado", "admirada", "admirado", "querer bem", "fascinação", "fascinante", "deslumbrante", 
    "atraente", "sedutor", "sedutora", "charmoso", "charmosa", "delícia", "delicioso", "deliciosa", "suave", 
    "doce", "mel", "flor", "florzinha", "estrela", "luz", "brilho", "brilhante", "anjinho", "anjo", "céu", 
    "paraíso", "sonho", "sonhar", "fantasia", "maravilhoso", "maravilhosa", "perfeito", "perfeita", "mágico", 
    "mágica", "fada", "príncipe", "princesa", "realeza", "majestade", "diamante", "pérola", "ouro", "bela", 
    "belo", "beleza", "adorável", "apaixonante", "apaixonar", "amante", "namorado", "namorada", "noivo", 
    "noiva", "esposo", "esposa", "companheiro", "companheira", "parceiro", "parceira", "unidos", "unidas", 
    "união", "juntos", "juntas", "eterno", "eterna", "sempre", "amor eterno", "amor verdadeiro", "verdadeira", 
    "verdadeiro", "amoroso", "amorosa", "apaixonante", "encantamento", "encantar", "cativar", "cativante", 
    "cativado", "cativada", "fascinar", "fascinado", "fascinada", "atrair", "atração", "seduzir", "sedução", 
    "conquistar", "conquista", "galanteador", "galanteio", "cortejar", "cortejo", "cuidado", "cuidar", 
    "proteger", "proteção", "segurança", "seguro", "segura", "abraçar", "abraço", "abraços", "envolver", 
    "envolvente", "envolvimento", "envolver-se", "entrelaçar", "entrelaçado", "entrelaçada", "laço", "laços", 
    "ligação", "ligar", "conectar", "conexão", "relacionar", "relacionamento", "relação", "companhia", "acompanhar", 
    "acompanhamento", "estar junto", "estar juntos", "juntar", "juntinho", "juntinhos", "coladinho", "coladinhos", 
    "colar", "colado", "colada", "apegado", "apegada", "apego", "vincular", "vínculo", "unir", "unido", "unida", 
    "união", "casal", "casamento", "casar", "noivar", "noivado", "noivos", "promessa", "prometer", "prometido", 
    "prometida", "fidelidade", "fiel", "lealdade", "leal", "confiança", "confiar", "confiante", "seguro", 
    "segurança", "proteção", "proteger", "cuidado", "cuidar", "amor", "amoroso", "amorosa", "carinho", 
    "carinhoso", "carinhosa", "afeto", "afetuoso", "afetuosa", "ternura", "terno", "terna", "doce", "doçura", 
    "meigo", "meiga", "meiguice", "gentil", "gentileza", "benevolente", "benevolência", "bondoso", "bondosa", 
    "bondade", "bom", "boa", "amável", "amabilidade", "agradável", "agradar", "agradecido", "agradecida", 
    "gratidão", "grato", "grata", "contente", "contentamento", "satisfeito", "satisfeita", "satisfação", 
    "feliz", "felicidade", "alegria", "alegre", "alegrar", "animado", "animada", "ânimo", "entusiasmo", 
    "entusiasmado", "entusiasmada", "excitado", "excitada", "excitação", "vibrante", "vibrar", "vibração", 
    "vivo", "viva", "vida", "vivacidade", "energia", "energético", "energética", "dinâmico", "dinâmica", 
    "dinamismo", "ativo", "ativa", "atividade", "ação", "agir", "empreender", "empreendimento", "iniciativa", 
    "iniciar", "começar", "começo", "principiar", "princípio", "início", "abrir", "abertura", "lançar", 
    "lançamento", "criar", "criação", "criativo", "criativa", "inovar", "inovação", "inovador", "inovadora", 
    "renovar", "renovação", "renovado", "renovada", "revigorar", "revigoramento", "revigorado", "revigorada", 
    "revigorante", "refrescar", "refrescante", "refresco", "refrescado", "refrescada", "reviver", "revivido", 
    "revivida", "revivência", "reavivar", "reavivado", "reavivada", "reanimar", "reanimado", "reanimada", 
    "reanimação", "reacender", "reaceso", "reacesa", "reacendimento", "resplandecer", "resplandecente", 
    "resplandecido", "resplandecida", "resplendor", "brilhar", "brilhante", "brilho", "radiante", "radiar", 
    "radiação", "luminoso", "luminosa"
}

SPECIAL_DATES = {
    # Put here special dates (e.g. Someone's birthday)
}
